// component_vars_sync.cpp —— 把 component_vars.kts 生成的定义合并进 mod 的 scripted_variables
//
// 用法（通常由 utils/gen_component_vars.sh 调用）：
//   component_vars_sync --target <mod>/common/scripted_variables/spth_component_variables.txt
//                       --attr  components_attributes.log
//                       --res   components_resources.log
//                       --scale components_scales.log [--dry-run] [--list] [--no-backup]
//
// 合并策略（原地合并，不做整文件重写）：
//   * 目标文件里已存在的 @name ：只替换等号右边的值，行尾注释与缩进原样保留；
//   * 目标文件里没有的 @name ：追加到文件末尾的托管块（BEGIN/END 注释标记）内，重复运行可幂等；
//   * 与本次生成无关的变量、注释、空行一律不动。
//
// 构建：g++ -std=c++17 -O2 -o component_vars_sync component_vars_sync.cpp

#include <algorithm>
#include <cctype>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <optional>
#include <set>
#include <sstream>
#include <stdexcept>
#include <string>
#include <vector>

namespace fs = std::filesystem;

namespace {

constexpr const char* kBlockBegin = "# >>> generated by utils/gen_component_vars.sh — BEGIN (do not edit inside) >>>";
constexpr const char* kBlockEnd   = "# <<< generated by utils/gen_component_vars.sh — END <<<";

struct Def {
    std::string name;
    std::string value;
    std::string source;   // 来自哪个生成文件，仅用于报告
};

std::string readFile(const fs::path& p) {
    std::ifstream in(p, std::ios::binary);
    if (!in) throw std::runtime_error("无法读取: " + p.string());
    std::ostringstream ss;
    ss << in.rdbuf();
    std::string s = ss.str();
    // 统一成 LF 处理，写回时保持 LF
    std::string out;
    out.reserve(s.size());
    for (char c : s) if (c != '\r') out.push_back(c);
    return out;
}

void writeFile(const fs::path& p, const std::string& content) {
    fs::create_directories(p.parent_path());
    std::ofstream out(p, std::ios::binary);
    if (!out) throw std::runtime_error("无法写入: " + p.string());
    out << content;
}

std::vector<std::string> splitLines(const std::string& text) {
    std::vector<std::string> lines;
    std::string cur;
    for (char c : text) {
        if (c == '\n') { lines.push_back(cur); cur.clear(); }
        else cur.push_back(c);
    }
    if (!cur.empty()) lines.push_back(cur);
    return lines;
}

std::string trim(const std::string& s) {
    size_t b = 0, e = s.size();
    while (b < e && std::isspace(static_cast<unsigned char>(s[b]))) ++b;
    while (e > b && std::isspace(static_cast<unsigned char>(s[e - 1]))) --e;
    return s.substr(b, e - b);
}

// 解析 "@name = value" 行：返回 {name, value, '#' 注释起始位置}
struct ParsedDef { std::string name, value; size_t commentPos; bool ok; };

ParsedDef parseDefLine(const std::string& line) {
    ParsedDef r{"", "", std::string::npos, false};
    size_t i = 0;
    while (i < line.size() && std::isspace(static_cast<unsigned char>(line[i]))) ++i;
    if (i >= line.size() || line[i] != '@') return r;
    size_t nameBegin = ++i;
    while (i < line.size() && (std::isalnum(static_cast<unsigned char>(line[i])) || line[i] == '_')) ++i;
    if (i == nameBegin) return r;
    r.name = line.substr(nameBegin, i - nameBegin);
    while (i < line.size() && std::isspace(static_cast<unsigned char>(line[i]))) ++i;
    if (i >= line.size() || line[i] != '=') return r;
    ++i;
    size_t valueBegin = i;
    while (i < line.size() && line[i] != '#') ++i;
    size_t valueEnd = i;
    r.commentPos = (i < line.size()) ? i : std::string::npos;
    std::string v = line.substr(valueBegin, valueEnd - valueBegin);
    // 去掉首尾空白
    r.value = trim(v);
    r.ok = true;
    return r;
}

std::vector<Def> loadGenerated(const fs::path& p, std::vector<std::string>& problems) {
    std::vector<Def> defs;
    if (!fs::exists(p)) { problems.push_back("缺少生成文件: " + p.string()); return defs; }
    std::set<std::string> seen;
    for (const auto& line : splitLines(readFile(p))) {
        auto d = parseDefLine(line);
        if (!d.ok) {
            if (!trim(line).empty() && trim(line)[0] != '#')
                problems.push_back(p.filename().string() + ": 无法解析的行: " + trim(line));
            continue;
        }
        if (!seen.insert(d.name).second)
            problems.push_back(p.filename().string() + ": 重复定义 " + d.name);
        defs.push_back({d.name, d.value, p.filename().string()});
    }
    return defs;
}

}  // namespace

int main(int argc, char** argv) {
    fs::path target, attrFile, resFile, scaleFile;
    bool dryRun = false, listChanges = false, backup = true;

    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        auto next = [&]() -> std::string {
            if (i + 1 >= argc) throw std::runtime_error("缺少参数: " + a);
            return argv[++i];
        };
        if (a == "--target") target = next();
        else if (a == "--attr") attrFile = next();
        else if (a == "--res") resFile = next();
        else if (a == "--scale") scaleFile = next();
        else if (a == "--dry-run") dryRun = true;
        else if (a == "--list") listChanges = true;
        else if (a == "--no-backup") backup = false;
        else if (a == "-h" || a == "--help") {
            std::cout << "用法: component_vars_sync --target <file> --attr <file> [--res <file>] "
                         "[--scale <file>] [--dry-run] [--list] [--no-backup]\n";
            return 0;
        } else {
            throw std::runtime_error("未知参数: " + a);
        }
    }

    try {
        if (target.empty()) throw std::runtime_error("必须指定 --target");
        if (attrFile.empty()) throw std::runtime_error("必须指定 --attr");

        std::vector<std::string> problems;
        std::vector<Def> generated = loadGenerated(attrFile, problems);
        if (!resFile.empty())   for (auto& d : loadGenerated(resFile, problems))   generated.push_back(d);
        if (!scaleFile.empty()) for (auto& d : loadGenerated(scaleFile, problems)) generated.push_back(d);

        std::string targetText = readFile(target);
        std::vector<std::string> lines = splitLines(targetText);

        std::map<std::string, size_t> index;
        for (size_t i = 0; i < lines.size(); ++i) {
            auto d = parseDefLine(lines[i]);
            if (d.ok && index.find(d.name) == index.end()) index[d.name] = i;
        }

        std::vector<std::pair<std::string, std::pair<std::string, std::string>>> updates;  // name, old, new
        std::map<std::string, std::string> toAppend;   // 顺序由 generated 决定
        std::vector<std::string> appendOrder;
        size_t unchanged = 0;

        for (const auto& def : generated) {
            auto it = index.find(def.name);
            if (it == index.end()) {
                if (toAppend.emplace(def.name, def.value).second) appendOrder.push_back(def.name);
                continue;
            }
            auto parsed = parseDefLine(lines[it->second]);
            if (parsed.value == def.value) { ++unchanged; continue; }

            // 只替换值，保留缩进/行尾注释
            std::string& line = lines[it->second];
            size_t eq = line.find('=');
            size_t valueEnd = (parsed.commentPos == std::string::npos) ? line.size() : parsed.commentPos;
            std::string tail = (parsed.commentPos == std::string::npos) ? "" : line.substr(parsed.commentPos);
            std::string head = line.substr(0, eq + 1);
            std::string newLine = head + " " + def.value;
            if (!tail.empty()) newLine += " " + tail;
            line = newLine;
            updates.push_back({def.name, {parsed.value, def.value}});
            (void)valueEnd;
        }

        // 追加块的定位
        size_t blockBegin = std::string::npos, blockEnd = std::string::npos;
        for (size_t i = 0; i < lines.size(); ++i) {
            if (blockBegin == std::string::npos && trim(lines[i]) == kBlockBegin) blockBegin = i;
            else if (blockBegin != std::string::npos && trim(lines[i]) == kBlockEnd) { blockEnd = i; break; }
        }

        std::vector<std::string> blockLines;
        if (!appendOrder.empty()) {
            blockLines.push_back(kBlockBegin);
            for (const auto& n : appendOrder) blockLines.push_back("@" + n + " = " + toAppend[n]);
            blockLines.push_back(kBlockEnd);
        }

        std::vector<std::string> out = lines;
        if (!blockLines.empty()) {
            if (blockBegin != std::string::npos && blockEnd != std::string::npos)
                out.erase(out.begin() + blockBegin, out.begin() + blockEnd + 1);
            else if (!out.empty() && trim(out.back()).empty()) out.pop_back();
            if (!out.empty() && !trim(out.back()).empty()) out.push_back("");
            out.insert(out.end(), blockLines.begin(), blockLines.end());
        }

        std::cout << "目标文件   : " << target.string() << "\n"
                  << "生成条目   : " << generated.size() << " 条"
                  << "（属性 " << (attrFile.empty() ? 0 : 1) << " 份";
        if (!resFile.empty()) std::cout << " + 资源";
        if (!scaleFile.empty()) std::cout << " + 缩放";
        std::cout << "）\n"
                  << "状态       : 未变 " << unchanged << "，更新 " << updates.size()
                  << "，新增 " << appendOrder.size() << "\n";

        if (listChanges) {
            for (auto& u : updates)
                std::cout << "   ~ " << u.first << ": " << u.second.first << " -> " << u.second.second << "\n";
            for (auto& n : appendOrder)
                std::cout << "   + " << n << " = " << toAppend[n] << "\n";
        }
        for (auto& p : problems) std::cout << "   [警告] " << p << "\n";

        if (updates.empty() && appendOrder.empty()) {
            std::cout << "结果       : 已经同步，无需写入\n";
            return 0;
        }
        if (dryRun) {
            std::cout << "结果       : --dry-run，未写入文件\n";
            return 0;
        }

        if (backup) {
            fs::path bak = target;
            bak += ".bak";
            writeFile(bak, targetText);
            std::cout << "备份       : " << bak.string() << "\n";
        }
        std::string joined;
        for (size_t i = 0; i < out.size(); ++i) { joined += out[i]; joined += "\n"; }
        writeFile(target, joined);
        std::cout << "结果       : 已写入 " << target.string() << "\n";
        return 0;
    } catch (const std::exception& e) {
        std::cerr << "错误: " << e.what() << "\n";
        return 1;
    }
}
