#!/bin/bash

generate()
{
  local ag_equip_key="$1"
  echo ""
  echo " ag_exploration_${ag_equip_key}:0 \"隙间物质存储模块\""
  echo " ag_exploration_${ag_equip_key}.desc:0 \"§L隙间用来存东西真是太方便不过了，可以为我们提供超乎想象的存储空间的同时还能随处取用。§!\n\""
  echo " ag_exploration_${ag_equip_key}.effect:0 \"携带资源上限 §G+\$@ag_exploration_resource_additional_touhou$§!\""
  echo " ag_exploration_${ag_equip_key}.remove_fail:0 \"§R携带资源不能超出上限。§!\""
  echo " ag_exploration_${ag_equip_key}.tooltip:0 \"-§Y\$ag_exploration_${ag_equip_key}$§!：[Root.ag_exploration_equipment_num_${ag_equip_key}s]\""
  echo " ag_exploration_${ag_equip_key}.num:0 \"\n§Y\$ag_exploration_${ag_equip_key}$§!：[Root.ag_exploration_equipment_num_${ag_equip_key}s]\""
  echo " ag_exploration.1.equipment.${ag_equip_key}:0 \"§H\$ag_exploration_${ag_equip_key}$§!\""
  echo " ag_exploration.1.equipment.${ag_equip_key}.max:0 \"§R\$ag_exploration_${ag_equip_key}$\$ag_exploration_cannot_more_than$\$@ag_exploration_${ag_equip_key}_max$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.max_tooltip:0 \"\n\$ag_exploration_max_amount$§Y\$@ag_exploration_${ag_equip_key}_max$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.integrity:0 \"\$ag_exploration_integrity$ §G+\$@ag_exploration_${ag_equip_key}_integrity_add$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.armament:0 \"\$ag_exploration_armament$ §R\$@ag_exploration_${ag_equip_key}_armament_add$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.investigator:0 \"\$ag_exploration_investigator$ §G+\$@ag_exploration_${ag_equip_key}_investigator_add$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.fleet_cap:0 \"\$ag_exploration_fleet_cap$ §R\$@ag_exploration_${ag_equip_key}_fleet_cap_add$§!\""
  echo " ag_exploration.1.effect.${ag_equip_key}.equipment_cap:0 \"\$ag_exploration_equipment_cap$ §R\$@ag_exploration_${ag_equip_key}_equipment_cap_add$§!\""
  echo " ag_exploration.1.cost.${ag_equip_key}.energy:0 \"£energy£§H\$energy$§! \$@ag_exploration_${ag_equip_key}_cost_energy$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.minerals:0 \"£minerals£§H\$minerals$§! \$@ag_exploration_${ag_equip_key}_cost_minerals$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.food:0 \"£food£§H\$food$§! \$@ag_exploration_${ag_equip_key}_cost_food$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.alloys:0 \"£alloys£§H\$alloys$§! \$@ag_exploration_${ag_equip_key}_cost_alloys$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.consumer_goods:0 \"£consumer_goods£§H\$consumer_goods$§! \$@ag_exploration_${ag_equip_key}_cost_consumer_goods$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.volatile_motes:0 \"£volatile_motes£§H\$volatile_motes$§! \$@ag_exploration_${ag_equip_key}_cost_volatile_motes$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.exotic_gases:0 \"£exotic_gases£§H\$exotic_gases$§! \$@ag_exploration_${ag_equip_key}_cost_exotic_gases$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.rare_crystals:0 \"£rare_crystals£§H\$rare_crystals$§! \$@ag_exploration_${ag_equip_key}_cost_rare_crystals$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.sr_living_metal:0 \"£sr_living_metal£§H\$sr_living_metal$§! \$@ag_exploration_${ag_equip_key}_cost_sr_living_metal$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.nanites:0 \"£nanites£§H\$nanites$§! \$@ag_exploration_${ag_equip_key}_cost_nanites$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.sr_dark_matter:0 \"£sr_dark_matter£§H\$sr_dark_matter$§! \$@ag_exploration_${ag_equip_key}_cost_sr_dark_matter$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.sr_zro:0 \"£sr_zro£§H\$sr_zro$§! \$@ag_exploration_${ag_equip_key}_cost_sr_zro$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.minor_artifacts:0 \"£minor_artifacts£§H\$minor_artifacts$§! \$@ag_exploration_${ag_equip_key}_cost_minor_artifacts$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.astral_threads:0 \"£astral_threads£§H\$astral_threads$§! \$@ag_exploration_${ag_equip_key}_cost_astral_threads$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.sr_lingli:0 \"£sr_lingli£§H\$sr_lingli$§! \$@ag_exploration_${ag_equip_key}_cost_sr_lingli$\""
  echo " ag_exploration.1.cost.${ag_equip_key}.sr_fuka:0 \"£sr_fuka£§H\$sr_fuka$§! \$@ag_exploration_${ag_equip_key}_cost_sr_fuka$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.energy:0 \"£energy£§H\$energy$§! \$@ag_exploration_${ag_equip_key}_upkeep_energy$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.minerals:0 \"£minerals£§H\$minerals$§! \$@ag_exploration_${ag_equip_key}_upkeep_minerals$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.food:0 \"£food£§H\$food$§! \$@ag_exploration_${ag_equip_key}_upkeep_food$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.alloys:0 \"£alloys£§H\$alloys$§! \$@ag_exploration_${ag_equip_key}_upkeep_alloys$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.consumer_goods:0 \"£consumer_goods£§H\$consumer_goods$§! \$@ag_exploration_${ag_equip_key}_upkeep_consumer_goods$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.volatile_motes:0 \"£volatile_motes£§H\$volatile_motes$§! \$@ag_exploration_${ag_equip_key}_upkeep_volatile_motes$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.exotic_gases:0 \"£exotic_gases£§H\$exotic_gases$§! \$@ag_exploration_${ag_equip_key}_upkeep_exotic_gases$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.rare_crystals:0 \"£rare_crystals£§H\$rare_crystals$§! \$@ag_exploration_${ag_equip_key}_upkeep_rare_crystals$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.sr_living_metal:0 \"£sr_living_metal£§H\$sr_living_metal$§! \$@ag_exploration_${ag_equip_key}_upkeep_sr_living_metal$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.nanites:0 \"£nanites£§H\$nanites$§! \$@ag_exploration_${ag_equip_key}_upkeep_nanites$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.sr_dark_matter:0 \"£sr_dark_matter£§H\$sr_dark_matter$§! \$@ag_exploration_${ag_equip_key}_upkeep_sr_dark_matter$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.sr_zro:0 \"£sr_zro£§H\$sr_zro$§! \$@ag_exploration_${ag_equip_key}_upkeep_sr_zro$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.minor_artifacts:0 \"£minor_artifacts£§H\$minor_artifacts$§! \$@ag_exploration_${ag_equip_key}_upkeep_minor_artifacts$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.astral_threads:0 \"£astral_threads£§H\$astral_threads$§! \$@ag_exploration_${ag_equip_key}_upkeep_astral_threads$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.sr_lingli:0 \"£sr_lingli£§H\$sr_lingli$§! \$@ag_exploration_${ag_equip_key}_upkeep_sr_lingli$\""
  echo " ag_exploration.1.upkeep.${ag_equip_key}.sr_fuka:0 \"£sr_fuka£§H\$sr_fuka$§! \$@ag_exploration_${ag_equip_key}_upkeep_sr_fuka$\""
}

generate kappa_expanded_shipyard
